set_property IOSTANDARD LVCMOS33 [get_ports {c[0]}]
set_property PACKAGE_PIN A21 [get_ports {c[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports s]
set_property PACKAGE_PIN W4 [get_ports a]
set_property PACKAGE_PIN R4 [get_ports b]
set_property PACKAGE_PIN Y9 [get_ports s]
